<?php
// $Id$

/**
 * This module provides a simple way to create forms and questionnaires.
 * 
 * The initial development of this module was sponsered by ÅF Industri AB, Open
 * Source City and Karlstad University Library. Continued development sponsored
 * by Lullabot.
 * 
 * @author Nathan Haug <nate@lullabot.com>
 * @author Pontus Ullgren <ullgren@user.sourceforge.net>
 */

/**
 * Implemenation of hook_help().
 */
function webform_help($section = "admin/help#webform") {
  $output =  "";
  switch ($section) {
    case 'admin/settings/webform' :
      $output = t("Webforms are forms and questionnaires. To add one select <strong>create content -&gt; webform</strong>. Below you can set different security and debug options.");
      break;
    case 'admin/help#webform' :
      $output = t("<p>This module lets you create forms or questionnaires and define their content. Submissions from these forms are stored in the database and optionally also sent by e-mail to a predefined address.</p>
      <p>Here is how to create one:</p>
      <ul>
       <li>Go to Create Content and add a webform</li>
       <li>Add a description to be displayed as a teaser and above the actual form.</li>
       <li>Add a confirmation message or redirect node that is to be displayed after successful submission.</li>
       <li>Add one or more components to your form.</li>
       <li>Optionally add an e-mail address to which submissions will be sent. If no email address is specified, no e-mail will be sent when submissions are made through the form.</li>
       <li>Optionally select an e-mail (or hidden) component that will be used to populate the return e-mail address on any sent e-mail.</li>
       <li>Optionally select a textfield (or hidden) component that will be used to populate the subject e-mail field on any sent e-mail.</li>
      </ul>
      <p>Help on adding and configuring the components will be shown after you add your first component.</p>
      <p>The content of submitted forms is stored in the database table <i>webform_submitted_data</i> as key-value pairs.</p>
      ");
      break;
    case 'node/add#webform' :
      $output = t("A webform can be a questionnaires, contact or request forms. It can be used to let visitors make contact, register for a event or to enable a complex survey.");
      break;
    case 'webform/helptext#variables' :
      $output = t('Available variables are: %username, %useremail, %site, %date.');
      $output .= ' '. t('You can also use %server[key] to add any of the special PHP <a href="http://www.php.net/reserved.variables#reserved.variables.server">$_SERVER</a> variables, %session[key] to add any of the special PHP <a href="http://www.php.net/reserved.variables#reserved.variables.session">$_SESSION</a> variables and %get[key] to create prefilled forms from from the <a href="http://www.php.net/reserved.variables#reserved.variables.get">URL</a>. %cookie, %request and %post also work with their respective PHP variables. For example %server[HTTP_USER_AGENT], %session[id], or %get[q].');
      if (module_exists('profile')) {
        $output .= ' '. t('If you are using the profiles module, you can also access all profile data using the syntax %profile[form_name]. If you for example have a profile value named profile_city, add the varible %profile[profile_city].');
      }
      break;
  }
  if (strstr($section, 'admin/settings/webform#')) {
    // Call help hooks in plugins:
    $components = webform_load_components(TRUE);
    foreach ($components as $component) {
      $help_function = "_webform_help_". $component;
      if (function_exists($help_function)) {
        $output .= $help_function($section);
      }
    }
  }

  // Node form help.
  if (arg(0) == 'node' && is_numeric(arg(1))) {
    if ($section == 'node/'. arg(1) .'/edit/components') {
      $output .= '<p>'. t('This page displays all the components currently configured for this webform node. You may add any number of components to the form, even multiple of the same type. To add a new component, fill in a name and select a type from the fields at the bottom of the table. Submit the form to create the new component or update any changed form values.') .'</p>';
      $output .= '<p>'. t('Click on any existing component\'s name to edit its settings.') .'</p>';
    }
  }
  return $output;
}

/**
 * Implementation of hook_menu().
 */
function webform_menu($may_cache) {
  global $user;

  $items = array();
  if ($may_cache) {
    // Submissions listing.
    $items[] = array(
      'path' => 'admin/content/webform',
      'title' => t('Webforms'),
      'callback' => 'webform_admin_content',
      'access' => user_access('access webform results'),
      'description' => t('View and edit all the available webforms on your site.'),
      'type' => MENU_NORMAL_ITEM,
    );

    // Admin Settings.
    $items[] = array(
      'path' => 'admin/settings/webform',
      'title' => t('Webform'),
      'callback' => 'drupal_get_form',
      'callback arguments' => 'webform_admin_settings',
      'access' => user_access('administer site configuration'),
      'description' => t('Global configuration of webform functionality.'),
      'type' => MENU_NORMAL_ITEM,
    );

    return $items;
  }
  elseif (arg(0) == 'node' && is_numeric(arg(1))) {
    $nid = arg(1);
    $node = node_load($nid);
    $sid = (arg(2) == 'submission' && is_numeric(arg(3))) ? arg(3) : NULL;

    if ($node->nid && $node->type == 'webform') {
      $items[] = array(
        'path' => 'node/'. $nid,
        'title' => $node->title, // Set the title for the node menu item.
        'callback' => 'node_page_view',
        'callback arguments' => array($node),
        'access' => TRUE,
        'type' => MENU_CALLBACK,
      );
      $items[] = array(
        'path' => 'node/'. $nid .'/done',
        'title' => t('Webform confirmation'),
        'callback' => '_webform_confirmation',
        'callback arguments' => array($node),
        'access' => node_access('view', $node),
        'type' => MENU_CALLBACK,
      );
      $items[] = array('path' => 'node/'. $nid .'/edit/configuration',
        'title' => t('Configuration'),
        'callback' => 'node_page_edit',
        'callback arguments' => array($node),
        'access' => node_access('update', $node),
        'weight' => 1,
        'type' => MENU_DEFAULT_LOCAL_TASK);
      $items[] = array(
        'path' => 'node/'. $nid .'/edit/components',
        'title' => t('Form components'),
        'callback' => 'webform_components',
        'callback arguments' => array($node),
        'access' => node_access('update', $node),
        'weight' => 2,
        'type' => MENU_LOCAL_TASK,
      );
      $items[] = array(
        'path' => 'node/'. $nid .'/results',
        'title' => t('Results'),
        'callback' => 'webform_results',
        'callback arguments' => array($node),
        'access' => user_access('access webform results'),
        'weight' => 2,
        'type' => MENU_LOCAL_TASK,
      );
      $items[] = array(
        'path' => 'node/'. $nid .'/results/submissions',
        'title' => t('Submissions'),
        'callback' => 'webform_results',
        'callback arguments' => array($node),
        'access' => user_access('access webform results'),
        'weight' => 4,
        'type' => MENU_DEFAULT_LOCAL_TASK,
      );
      $items[] = array(
        'path' => 'node/'. $nid .'/results/analysis',
        'title' => t('Analysis'),
        'callback' => 'webform_results',
        'callback arguments' => array($node, 'analysis'),
        'access' => user_access('access webform results'),
        'weight' => 5,
        'type' => MENU_LOCAL_TASK,
      );
      $items[] = array(
        'path' => 'node/'. $nid .'/results/table',
        'title' => t('Table'),
        'callback' => 'webform_results',
        'callback arguments' => array($node, 'table'),
        'access' => user_access('access webform results'),
        'weight' => 6,
        'type' => MENU_LOCAL_TASK,
      );
      $items[] = array(
        'path' => 'node/'. $nid .'/results/download',
        'title' => t('Download'),
        'callback' => 'webform_results',
        'callback arguments' => array($node, 'download'),
        'access' => user_access('access webform results'),
        'weight' => 7,
        'type' => MENU_LOCAL_TASK,
      );
      $items[] = array(
        'path' => 'node/'. $nid .'/results/clear',
        'title' => t('Clear'),
        'callback' => 'webform_results',
        'callback arguments' => array($node, 'clear'),
        'access' => user_access('clear webform results'),
        'weight' => 8,
        'type' => MENU_LOCAL_TASK,
      );
      if (isset($sid)) {
        include_once(drupal_get_path('module', 'webform') ."/webform_submissions.inc");
        $submission = webform_get_submission($node->nid, $sid);

        $items[] = array(
          'path' => 'node/'. $nid .'/submission/'. $sid,
          'title' => t('Webform submission'),
          'callback' => 'drupal_get_form',
          'callback arguments' => array('webform_client_form_'. $node->nid, $node, $submission),
          'access' => webform_submission_access($node, $submission, 'view'),
          'type' => MENU_CALLBACK,
        );
        $items[] = array(
          'path' => 'node/'. $nid .'/submission/'. $sid .'/view',
          'title' => t('View'),
          'callback' => 'drupal_get_form',
          'callback arguments' => array('webform_client_form_'. $node->nid, $node, $submission),
          'access' => webform_submission_access($node, $submission, 'view'),
          'weight' => 0,
          'type' => MENU_DEFAULT_LOCAL_TASK,
        );
        $items[] = array(
          'path' => 'node/'. $nid .'/submission/'. $sid .'/edit',
          'title' => t('Edit'),
          'callback' => 'drupal_get_form',
          'callback arguments' => array('webform_client_form_'. $node->nid, $node, $submission, TRUE),
          'access' => webform_submission_access($node, $submission, 'edit'),
          'weight' => 1,
          'type' => MENU_LOCAL_TASK,
        );
        $items[] = array(
          'path' => 'node/'. $nid .'/submission/'. $sid .'/delete',
          'title' => t('Delete'),
          'callback' => 'drupal_get_form',
          'callback arguments' => array('webform_submission_delete_form', $node->nid, $submission['sid']),
          'access' => webform_submission_access($node, $submission, 'delete'),
          'weight' => 2,
          'type' => MENU_LOCAL_TASK,
        );
      }
    }
  }

  return $items;
}

/**
 * Implementation of hook_perm().
 */
function webform_perm() {
  return array("create webforms", "edit own webforms", "edit webforms", "access webform results", "clear webform results", "access own webform submissions", "edit own webform submissions", "edit webform submissions", "use PHP for additional processing");
}

/**
 * Implementation of hook_node_info().
 */
function webform_node_info() {
  return array(
    'webform' => array(
      'name' => t('Webform'),
      'module' => 'webform',
      'description' => t('Create a new form or questionnaire accessible to users. Submission results and statistics are recorded and accessible to privileged users.'),
    )
  );
}

/**
 * Implemenation of hook_access().
 */
function webform_access($op, $node) {
  global $user;

  switch ($op) {
    case "create":
      return user_access("create webforms");
    case "update":
    case "delete":
      return user_access("edit webforms") || (user_access("edit own webforms") && ($user->uid == $node->uid));
  }
}

/**
 * Implementation of hook_forms().
 * All webform_client_form forms share the same form handler
 */
function webform_forms($args) {
  $form_id = $args[0];
  if (strpos($form_id, 'webform_client_form_') === 0) {
    $forms[$form_id]['callback'] = 'webform_client_form';
  }
  return $forms;
}

/**
 * Implementation of hook_file_download().
 * 
 * Only allow users with view webform submissions to download files.
 */
function webform_file_download($file) {
  if (strpos($file, variable_get('file_directory_path', 'files') .'/webform/') === 0 && user_access('access webform results')) {
    $info = image_get_info(file_create_path($file));
    return array('Content-type: '. $info['mime_type']);
  }
}

/**
 * Implemenation of hook_insert().
 */
function webform_insert($node) {
  global $user;

  // Correctly set the submission limits.
  if ($_POST['enforce_limit'] === 'no') {
    $node->submit_limit = '-1';
    $node->submit_interval = '157784630'; // 5 years, close enough to 'ever'.
  }

  // Insert the Webform.
  db_query("INSERT INTO {webform} (nid, confirmation, redirect_post, submit_limit, submit_interval, email, email_from_name, email_from_address, email_subject, additional_validate, additional_submit) VALUES (%d, '%s', %d, %d, %d, '%s', '%s', '%s', '%s', '%s', '%s')", $node->nid, $node->confirmation, $node->redirect_post, $node->submit_limit, $node->submit_interval, $node->email, $node->email_from_name, $node->email_from_address, $node->email_subject, $node->additional_validate, $node->additional_submit);

  // Insert the components into the database.
  if (is_array($node->webformcomponents) && !empty($node->webformcomponents)) {
    foreach ($node->webformcomponents as $cid => $component) {
      db_query("INSERT INTO {webform_component} (nid, cid, pid, form_key, name, type, value, extra, mandatory, weight) VALUES (%d, %d, %d, '%s', '%s', '%s', '%s', '%s', %d, %d)",
        $node->nid, $cid, $component['pid'], $component['form_key'], $component['name'], $component['type'], $component['value'], serialize($component['extra']), ($component['mandatory'] ? 1 : 0), $component['weight']
      );
    }
  }
}

/**
 * Implemenation of hook_update().
 */
function webform_update($node) {
  // Update the webform by deleting existing data and replacing with the new.
  db_query("DELETE FROM {webform} WHERE nid = %d", $node->nid);
  db_query("DELETE FROM {webform_component} WHERE nid = %d", $node->nid);
  webform_insert($node);
}

/**
 * Implemenation of hook_delete().
 */
function webform_delete(&$node) {
  db_query("DELETE FROM {webform} WHERE nid = %d", $node->nid);
  db_query("DELETE FROM {webform_component} WHERE nid = %d", $node->nid);
  watchdog('webform', 'webform "'. $node->title .'" deleted', WATCHDOG_NOTICE);
}

/**
 * Implemenation of hook_load().
 */
function webform_load($node) {
  $additions = db_fetch_object(db_query("SELECT * FROM {webform} WHERE nid = %d", $node->nid));
  $additions->webformcomponents = array();
  $result = db_query('SELECT * FROM {webform_component} WHERE nid = %d ORDER BY weight, name', $node->nid);
  while ($c = db_fetch_array($result)) {
    $component =& $additions->webformcomponents[$c['cid']];
    $component['cid'] = $c['cid'];
    $component['form_key'] = $c['form_key'] ? $c['form_key'] : $c['cid'];
    $component['name'] = t($c['name']);
    $component['type'] = $c['type'];
    $component['value'] = $c['value'];
    $component['extra'] = unserialize($c['extra']);
    $component['mandatory'] = $c['mandatory'];
    $component['pid'] = $c['pid'];
    $component['weight'] = $c['weight'];
  }

  // Organize the components into a fieldset-based order.
  if (!empty($additions->webformcomponents)) {
    $component_tree = array();
    $page_count = 1;
    _webform_components_tree_build($additions->webformcomponents, $component_tree, 0, $page_count);
    $additions->webformcomponents = _webform_components_tree_flatten($component_tree['children']);
  }
  return $additions;
}

/**
 * Implementation of hook_link().
 * Always add a "view form" link.
 */
function webform_link($type, $node = 0, $main = 0) {
  if ($node->type == 'webform') {
    if ($main == 1) {
      $links['webform_goto'] = array(
        'title' => t('Go to form'),
        'href' => "node/$node->nid",
        'attributes' => array('title' => t('View this form.'), 'class' => 'read-more')
      );
    }
  }
  return $links;
}

/**
 * Implementation of hook_form()
 * Creates the standard form for editing or creating a webform.
 */
function webform_form(&$node, &$param) {
  /* Start Edit Form */
  $form['webform'] = array(
    '#type' => 'fieldset',
    '#title' => t('Webform Settings'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#weight' => -4
  );

  $form['webform']['title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title'),
    '#default_value' => $node->title,
    '#maxlength' => 128,
    '#required' => TRUE,
  );

  $form['webform']['body'] = array(
    '#type' => 'textarea',
    '#title' => t('Description'),
    '#description' => t('Text to be shown as teaser and before the form.'),
    '#default_value' => $node->body,
    '#cols' => 40,
    '#rows' => 10,
    '#required' => TRUE,
  );

  $form['webform']['confirmation'] = array(
    '#type' => 'textarea',
    '#title' => t("Confirmation message or redirect URL"),
    '#description' => t("Message to be shown upon successful submission or a path to a redirect page. Redirect pages must start with <em>http://</em> for external sites or <em>internal:</em> for an internal path. i.e. <em>http://www.example.com</em> or <em>internal:node/10</em>"),
    '#default_value' => $node->confirmation,
    '#cols' => 40,
    '#rows' => 10,
    '#required' => TRUE,
  );

  $form['webform']['format'] = filter_form($node->format);
  /* End Edit Form */

  /* Start E-mail Settings Form */
  $form['mailsettings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Mail Settings'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#weight' => -2,
  );

  $form['mailsettings']['email'] = array(
    '#type' => 'textfield',
    '#title' => t("E-mail to address"),
    '#default_value' => $node->email,
    '#description' => t('Form submissions will be e-mailed to this address. Leave blank for none.'),
  );

  // Build arrays of possible return email addresses and email subject lines from elements on the form.
  $possible_email_from_name = array('default' => variable_get('webform_default_from_name', variable_get('site_name', '')) .' ['. t('Default') .']', 'none' => '['. t('None') .']');
  $possible_email_from_address = array('default' => variable_get('webform_default_from_email', variable_get('site_mail', ini_get('sendmail_from'))) .' ['. t('Default') .']', 'none' => '['. t('None') .']');
  $possible_email_subject = array('default' => variable_get('webform_default_subject', t('Form submission from: ') . t('$title')) .' ['. t('Default') .']', 'none' => '['. t('None') .']');

  if (is_array($node->webformcomponents) && !empty($node->webformcomponents)) {
    foreach ($node->webformcomponents as $cid => $component) {
      $type = $component['type'];
      if (in_array($type, array('textfield', 'hidden', 'select'))) {
        $possible_email_from_name[$component['name']] = $component['name'];
        $possible_email_subject[$component['name']] = $component['name'];
      }
      if (in_array($type, array('email', 'hidden', 'select'))) {
        $possible_email_from_address[$component['name']] = $component['name'];
      }
    }
  }

  $form['mailsettings']['email_from_name'] = array(
    '#type' => 'select',
    '#title' => t('E-mail from name'),
    '#default_value' => $node->email_from_name,
    '#options' => $possible_email_from_name,
    '#description' => t('After adding components to this form, any textfield or hidden form element may be selected as the sender\'s name for e-mails.'),
    '#weight' => 6,
  );
  $form['mailsettings']['email_from_address'] = array(
    '#type' => 'select',
    '#title' => t('E-mail from address'),
    '#default_value' => $node->email_from_address,
    '#options' => $possible_email_from_address,
    '#description' => t('After adding components to this form, any e-mail or hidden form element may be selected as the sender\'s address for e-mails.'),
    '#weight' => 7,
  );
  $form['mailsettings']['email_subject'] = array(
    '#type' => 'select',
    '#title' => t('E-mail subject'),
    '#default_value' => $node->email_subject,
    '#options' => $possible_email_subject,
    '#description' => t('After adding components to this form, any textfield or hidden form element may be selected as the subject line for e-mails.'),
    '#weight' => 8,
  );
  /* End mail settings form */

  /* Start advanced settings form */
  $form['advanced'] = array(
    '#type' => 'fieldset',
    '#title' => t('Advanced Settings'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#weight' => -1
  );
  $form['advanced']['submitlimit'] = array(
    '#type' => 'fieldset',
    '#title' => t('Limit the number of submission a user may send within a specified time period.'),
    '#prefix' => '<div class="container-inline">',
    '#suffix' => '</div>',
  );
  $form['advanced']['submitlimit']['unlimited'] = array(
    '#name' => 'enforce_limit', // Override the naming scheme to force these radios into the same group.
    '#type' => 'radio',
    '#return_value' => 'no',
    '#title' => t('Unlimited'),
    '#default_value' => ($node->submit_limit > 0 ? false : 'no'),
    '#parents' => array('advanced', 'submitlimit'), // If we don't specify the parent, the forms API will think this is an illegal posting.
  );
  $form['advanced']['submitlimit']['limited'] = array(
    '#name' => 'enforce_limit', // Override the naming scheme to force these radios into the same group.
    '#type' => 'radio',
    '#return_value' => 'yes',
    '#prefix' => '<br />',
    '#suffix' => t('Limit to '),
    '#default_value' => ($node->submit_limit > 0 ? 'yes' : false),
    '#parents' => array('advanced', 'submitlimit'), // If we don't specify the parent, the forms API will think this is an illegal posting.
  );
  $form['advanced']['submitlimit']['submit_limit'] = array(
    '#type' => 'textfield',
    '#maxlength' => 2,
    '#size' => 2,
    '#suffix' => ' '. t('submission(s)') .' ',
    '#default_value' => ($node->submit_limit > 0 ? $node->submit_limit : ""),
    '#attributes' => array(
      'style' => 'width: 2em; display: inline;',
      'onchange' => "javascript: document.getElementsByName('enforce_limit').item(1).checked = true;",
      'onclick' => "javascript: document.getElementsByName('enforce_limit').item(1).checked = true;"
    ),
  );
  $form['advanced']['submitlimit']['submit_interval'] = array(
    '#type' => 'select',
    '#options' => array(
      '157784630' => t('ever'), // 5 years.
      '1600' => t('every hour'),
      '86400' => t('every day'),
      '604800' => t('every week'),
    ),
    '#default_value' => $node->submit_interval,
    '#attributes' => array(
      'onchange' => "javascript: document.getElementsByName('enforce_limit').item(1).checked = true;",
      'onclick' => "javascript: document.getElementsByName('enforce_limit').item(1).checked = true;"
    ),
  );

  if (user_access('use PHP for additional processing')) {
    $form['advanced']['additional_validate'] = array(
      '#type' => 'textarea',
      '#title' => 'Additional Validation',
      '#description' => t('Enter PHP code to preform additional validation for this form. Include the &lt;?php ?&gt; tags. $form_id and $form_values are available variables. If validation fails, use the form_set_error function to prevent the form from being submitted. Use the same syntax as a _validate function used in the <a href="http://api.drupal.org/api/file/developer/topics/forms_api.html">Forms API</a>.'),
      '#default_value' => $node->additional_validate,
      '#cols' => 40,
      '#rows' => 10,
    );

    $form['advanced']['additional_submit'] = array(
      '#type' => 'textarea',
      '#title' => 'Additional Processing',
      '#description' => t('Enter PHP code to preform additional processing for this form (after the validation). Include the &lt;?php ?&gt; tags. $form_id and $form_values are available variables, use the same syntax as a _submit function used in the <a href="http://api.drupal.org/api/file/developer/topics/forms_api.html">Forms API</a>.'),
      '#default_value' => $node->additional_submit,
      '#cols' => 40,
      '#rows' => 10,
    );
  }
  else {
    $form['advanced']['additional_validate'] = array(
      '#type' => 'value',
      '#value' => $node->additional_validate,
    );

    $form['advanced']['additional_submit'] = array(
      '#type' => 'value',
      '#value' => $node->additional_submit,
    );
  }
  $form['advanced']['redirect_post'] = array(
    '#type' => 'checkbox',
    '#title' => t("Redirect POST Values"),
    '#description' => t("Forward the contents of the POST array to the redirect URL. Use this option for custom processing of the form information. No processing will be done by webform. The confirmation option above MUST be a full redirect URL for this option to have an effect."),
    '#default_value' => $node->redirect_post,
  );
  /* End Advanced Settings Form */

  return $form;
}

/**
 * Implementation of hook_view().
 */
function webform_view(&$node, $teaser = 0, $page = 0) {
  global $user;

  // If a teaser, do not display the form.
  if ($teaser) {
    $node->content['teaser'] = array('#value' => check_markup($node->teaser, $node->format, FALSE));
    return $node;
  }

  $sid_to_display = isset($_GET['sid']) ? $_GET['sid'] : NULL;
  $submission = array();
  $enabled = FALSE;
  $preview = FALSE;

  if ($_POST['op'] == t('Preview')) {
    $preview = true;
    $additions = webform_load($node);
    $node->webformcomponents = $additions->webformcomponents;
  }

  if (isset($sid_to_display) && is_numeric($sid_to_display)) {
    include_once(drupal_get_path('module', 'webform') ."/webform_submissions.inc");
    $submission = webform_get_submission($node->nid, $sid_to_display);
    $enabled = isset($_GET['op']) && $_GET['op'] == 'edit' && ((user_access('edit own webform submissions') && $submission['uid'] == $user->uid) || user_access('edit webform submissions'));
    if (!$enabled && (!user_access('access webform results') && !(user_access('access own webform submissions') && $submission['uid'] == $user->uid))) {
      $submission = array();
    }
    else {
      drupal_set_title('Submission #'. $sid_to_display);
      $node->body = "";
    }
  }

  $output = drupal_get_form('webform_client_form_'. $node->nid, $node, $submission, $enabled, $preview);

  // Remove the surrounding <form> tag if this is a preview.
  if ($preview) {
    $output = preg_replace('/<\/?form[^>]*>/', '', $output);
  }

  $node->content['body'] = array('#value' => check_markup($node->body, $node->format, FALSE));
  $node->content['webform'] = array('#value' => $output, '#weight' => 1);

  return $node;
}

/**
 * Menu callback for admin/webform/settings.
 */
function webform_admin_settings() {
  $form['components'] = array(
    '#type' => 'fieldset',
    '#title' => t('Available Components'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#description' => t('Below is a list of supported field types available for webform. You may disable any of these components by unchecking its corresponding box. Only checked components will be available in existing or new webforms.'),
  );

  // Add each component to the form:
  $component_types = webform_load_components(TRUE);
  foreach ($component_types as $component_name => $component_trans_name) {
    $form['components']['webform_enable_'. $component_name] = array(
      '#title' => $component_trans_name,
      '#description' => module_invoke('webform', 'help', 'admin/settings/webform#'. $component_name .'_description'),
      '#type' => 'checkbox',
      '#checked_value' => 1,
      '#default_value' => variable_get('webform_enable_'. $component_name, 1),
    );
  }

  $form['email'] = array(
    '#type' => 'fieldset',
    '#title' => t('Default E-mail Values'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form['email']['webform_default_from_email']  = array(
    '#type' => 'textfield',
    '#title' => t("From e-mail address"),
    '#default_value' => variable_get('webform_default_from_email', variable_get('site_mail', ini_get('sendmail_from'))),
    '#description' => t('Default sender address. This may be the E-mail address of the maintainer of your forms. This is also used for Reply-To, Return-Path and Errors-To.'),
  );

  $form['email']['webform_default_from_name']  = array(
    '#type' => 'textfield',
    '#title' => t("From Name"),
    '#default_value' => variable_get('webform_default_from_name', variable_get('site_name', '')),
    '#description' => t('Default sender name which is displayed together with the E-mail address.'),
  );

  $form['email']['webform_default_subject']  = array(
    '#type' => 'textfield',
    '#title' => t("Default Subject"),
    '#default_value' => variable_get('webform_default_subject', t('Form submission from: ')),
    '#description' => t('Default Subject. If not other stated in the form configuration this is appended to your form title. If you have e.g. defined "Your " (note the space) as a default subject and a form titled with "Order" the e-mail subject will be "Your Order".'),
  );

  $form['advanced'] = array(
    '#type' => 'fieldset',
    '#title' => t('Advanced Options'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  $form['advanced']['webform_use_cookies']  = array(
    '#type' => 'checkbox',
    '#checked_value' => 1,
    '#title' => t("Allow Cookies for Tracking Submissions"),
    '#default_value' => variable_get("webform_use_cookies", 0),
    '#description' => t('<a href="http://www.wikipedia.org/wiki/HTTP_cookie">Cookies</a> can be used to help prevent the same user from repeatedly submitting a webform. This feature is not needed for limiting submissions per user, though it can increase accuracy in some situations. Besides cookies, webform also uses IP addresses and site usernames to prevent repeated submissions.'),
  );

  $form['advanced']['webform_debug']  = array(
    '#type' => 'select',
    '#title' => t("Webforms Debug"),
    '#default_value' => variable_get("webform_debug", 0),
    '#options' => array(0 => t("OFF"), 1 => t("Log submissions"), 2 => t("Full debug")),
    '#description' => t('Set this option to "Log submissions" to log all submissions in the watchdog. Set it to "Full debug" to print debug info on submission. You probably want to leave this option on "OFF".')
  );
  return system_settings_form($form);
}

function theme_webform_admin_settings($form) {
  // Format the components into a table.
  foreach (element_children($form['components']) as $key) {
    $row = array();
    $row[] = $form['components'][$key]['#title'];
    $row[] = $form['components'][$key]['#description'];
    unset($form['components'][$key]['#title']);
    unset($form['components'][$key]['#description']);
    $row[] = array('data' => drupal_render($form['components'][$key]), 'align' => 'center');
    $rows[] = $row;
  }
  $header = array(t('Name'), t('Description'), t('Enabled'));

  // Create the table inside the form.
  $form['components']['table'] = array(
    '#value' => theme('table', $header, $rows)
  );

  $output = drupal_render($form);
  return $output;
}

/**
 * Client form generation function. If this is displaying an existing
 * submission, pass in the $submission variable with the contents of the
 * submission to be displayed.
 * 
 * @param $node
 *   The current webform node.
 * @param $submission
 *   Optional. An array of values for the form if we're displaying a result.
 * @param $enabled
 *   Optional. If displaying a result, specify if form elements are enabled for
 *   editing.
 * @param $form_values
 *   The current form values of a submission, used in multipage webforms.
 */
function webform_client_form(&$node, $submission = array(), $enabled = FALSE, $preview = FALSE, $form_values = NULL) {
  global $user;

  include_once(drupal_get_path('module', 'webform') .'/webform_components.inc');
  webform_load_components();

  if ($submission['sid']) {
    drupal_set_title('Submission #'. $submission['sid']);
  }

  if (module_exists('profile')) {
    profile_load_profile($user);
  }

  if ($node->redirect_post && (valid_url(trim($node->confirmation), true) || preg_match('/^internal:/', $node->confirmation))) {
    $form['#action'] = trim($node->confirmation);
  }

  // Set a header for navigating results.
  if ($submission && user_access('access webform results')) {
    // Add CSS to display submission info. Don't preprocess because this CSS file is used rarely.
    drupal_add_css(drupal_get_path('module', 'webform') .'/webform.css', 'module', 'all', FALSE);

    $previous = db_result(db_query('SELECT MAX(sid) FROM {webform_submissions} WHERE nid = %d AND sid < %d', array($node->nid, $submission['sid'])));
    $next = db_result(db_query('SELECT MIN(sid) FROM {webform_submissions} WHERE nid = %d AND sid > %d', array($node->nid, $submission['sid'])));

    $form['navigation'] = array(
      '#prefix' => '<div class="webform-submission-navigation">',
      '#suffix' => '</div>',
    );
    $form['navigation']['previous'] = array(
      '#value' => $previous ? l(t('Previous submission'), 'node/'. $node->nid .'/submission/'. $previous . ($enabled ? '/edit' : '') , array('class' => 'webform-submission-previous')) : '<span class="webform-submission-previous">'. t('Previous submission') .'</span>',
    );
    $form['navigation']['next'] = array(
      '#value' => $next ? l(t('Next submission'), 'node/'. $node->nid .'/submission/'. $next . ($enabled ? '/edit' : ''), array('class' => 'webform-submission-next')) : '<span class="webform-submission-next">'. t('Next submission') .'</span>',
    );

    $form['submission_info'] = array(
      '#title' => t('Submission Information'),
      '#type' => 'fieldset',
      '#collapsible' => FALSE,
    );
    $account = user_load(array('uid' => $submission['uid']));
    $form['submission_info']['user_picture'] = array(
      '#value' => theme('user_picture', $account),
    );
    $form['submission_info']['form'] = array(
      '#value' => '<div>'. t('Form: !form', array('!form' => l($node->title, 'node/'. $node->nid))) .'</div>',
    );
    $form['submission_info']['submitted'] = array(
      '#value' => '<div>'. t('Submitted by !name', array('!name' => theme('username', $account))) .'</div>',
    );
    $form['submission_info']['time'] = array(
      '#value' => '<div>'. format_date($submission['submitted'], 'large') .'</div>',
    );
    $form['submission_info']['ip_address'] = array(
      '#value' => '<div>'. $submission['remote_addr'] .'</div>',
    );
  }

  // Add a theme function for this form.
  $form['#theme'] = 'webform_form_'. $node->nid;
  // Set the encoding type (necessary for file uploads).
  $form['#attributes']['enctype'] = 'multipart/form-data';
  $form['#base'] = 'webform_client_form';

  if (is_array($node->webformcomponents) && !empty($node->webformcomponents)) {
    // Prepare a new form array.
    $form['submitted'] = array(
      '#tree' => TRUE
    );
    $form['details'] = array(
      '#tree' => true,
    );

    // Put the components into a tree structure.
    $component_tree = array();
    $page_count = 1;
    $page_num = 1;
    _webform_components_tree_build($node->webformcomponents, $component_tree, 0, $page_count);

    if ((!$preview && empty($submission)) || ($enabled)) {
      if ($page_count > 1) {
        $next_page = t('Next Page >');
        $prev_page = t('< Previous Page');
        if (isset($form_values)) {
          $page_num = $form_values['details']['page_num'];
          if ($form_values['op'] == $prev_page && $page_num > 1) {
            $page_num--;
          }
          else if ($form_values['op'] == $next_page && $page_num < $page_count) {
            $page_num++;
          }
        }
        else {
          $page_num = 1;
        }

        $form['#multistep'] = TRUE;
        if ($_POST['op'] != t('Submit')) {
          $form['#redirect'] = FALSE;
        }

        $form['details']['page_num'] = array(
          '#type'      => 'hidden',
          '#value'     => $page_num,
        );
        // Add the submit button(s).
        if ($page_num > 1) {
          $form['submitbutton_prev'] = array(
            '#type' => 'submit',
            '#value' => $prev_page,
            '#weight' => 1000,
          );
        }
        if ($page_num == $page_count) {
          $form['submitbutton'] = array(
            '#type' => 'submit',
            '#value' => t('Submit'),
            '#weight' => 1001,
          );
        }
        else if ($page_num < $page_count) {
          $form['submitbutton_next'] = array(
            '#type' => 'submit',
            '#value' => $next_page,
            '#weight' => 1001,
          );
        }
      }
      else {
        $page_num = 1;
        // Add the submit button.
        $form['submitbutton'] = array(
          '#type' => 'submit',
          '#value' => t('Submit'),
          '#weight' => 1000,
        );
      }
    }

    // Recursively add components to the form. Microweights keep thins in webform order.
    $microweight = 0.001;
    foreach ($component_tree['children'] as $cid => $component) {
      _webform_client_form_add_component($cid, $component, $form['submitted'], $form, $submission, $page_num, $enabled);
      $form['submitted'][$component['form_key']]['#weight'] += $microweight;
      $microweight += 0.001;
    }
    // Do not display the submit button if this is a preview or submission view.
    if ((!$preview && empty($submission)) || ($enabled)) {
      // Additional hidden elements.
      $form['details']['email_subject'] = array(
        '#type'      => 'hidden',
        '#value'     => $node->email_subject,
      );
      $form['details']['email_from_name'] = array(
        '#type'      => 'hidden',
        '#value'     => $node->email_from_name,
      );
      $form['details']['email_from_address'] = array(
        '#type'      => 'hidden',
        '#value'     => $node->email_from_address,
      );
      $form['details']['nid'] = array(
        '#type'      => 'value',
        '#value'     => $node->nid,
      );
      if (array_key_exists('sid', $submission)) {
        $form['details']['sid'] = array(
          '#type'      => 'hidden',
          '#value'     => $submission['sid'],
        );
      }      
    }
  }

  return $form;
}

function _webform_client_form_add_component($cid, $component, &$parent_fieldset, &$form, $submission, $page_num, $enabled = false) {
  // Load with submission information if necessary.
  if (!empty($submission) && !$enabled) {
    // This component is display only, with the value set according information
    // previously submitted in the submission numbered $sid_to_display.
    $display_function = "_webform_submission_display_". $component['type'];
    if (function_exists($display_function)) {
      $parent_fieldset[$component['form_key']] = $display_function($submission['data'][$cid], $component, $enabled);
    }
  }
  else if ($component['page_num'] == $page_num) {
    // Add this user-defined field to the form (with all the values that are always available).
    if ($enabled) {
      $display_function = "_webform_submission_display_". $component['type'];
      if (function_exists($display_function)) {
        $parent_fieldset[$component['form_key']] = $display_function($submission['data'][$cid], $component, $enabled);
      }
    }
    else {
      $render_function = "_webform_render_". $component['type'];
      if (function_exists($render_function)) {
        $parent_fieldset[$component['form_key']] = $render_function($component); // Call the component render function.
      }
      else {
        drupal_set_message(t("The webform component @type is not able to be displayed", array('@type' => $component['type'])));
      }
    }
  }
  if (is_array($component['children'])) {
    $microweight = 0.001;
    foreach ($component['children'] as $scid => $subcomponent) {
      _webform_client_form_add_component($scid, $subcomponent, $parent_fieldset[$component['form_key']], $form, $submission, $page_num, $enabled);
      $parent_fieldset[$component['form_key']][$subcomponent['form_key']]['#weight'] += $microweight;
      $microweight += 0.001;
    }
  }
}

function webform_client_form_validate($form_id, $form_values) {
  global $user;
  include_once(drupal_get_path('module', 'webform') ."/webform_submissions.inc");

  $node = node_load(array('nid' => $form_values['details']['nid']));

  // Flatten trees within the submission.
  $form_values['submitted_tree'] = $form_values['submitted'];
  _webform_client_form_submit_flatten($node, $form_values['submitted'], $form_values['submitted']);

  // Verify that this submission is within the submission limits on this form.
  if ($violation_count = _webform_submission_limit_check($node, $form_values) && !$form_values['details']['sid']) {
    // If the webform is being swamped by repeated entries, limit the messages in watchdog.
    if ($violation_count < 21) {
      if ($user->uid > 0) {
        watchdog('webform', t('The authenticated user <a href="%user_url">%username</a> attempted to submit more entries than allowed on the <a href="%webform_url">%webform_title</a> webform',
                              array(
                                '%user_url' => url('user/'. $user->uid),
                                '%username' => $user->name,
                                '%webform_url' => url('node/'. $node->nid),
                                '%webform_title' => $node->title,
                              )), WATCHDOG_WARNING);
      }
      else {
        watchdog('webform', t('An anonymous user with IP address %ip attempted to submit more entries than allowed on the <a href="%webform_url">%webform_title</a> webform',
                              array(
                                '%ip' => $_SERVER['REMOTE_ADDR'],
                                '%webform_url' => url('node/'. $node->nid),
                                '%webform_title' => $node->title,
                              )), WATCHDOG_WARNING);
      }
    }
    form_set_error('', t("You have submitted the maximum number of entries. Check submission guidelines."));
  }

  if (trim($node->additional_validate)) {
    // We use eval here (rather than drupal_eval) because the user needs access to local variables.
    eval("?>". $node->additional_validate);
  }
}

function webform_client_form_submit($form_id, $form_values) {
  global $user, $base_url;
  include_once(drupal_get_path('module', 'webform') ."/webform_submissions.inc");

  $node = node_load(array('nid' => $form_values['details']['nid']));
  $session_key = 'webform_form_'. $node->nid;

  if ($form_values['op'] != t('Submit')) {
    // This is a multi-page form that is not yet complete.
    // Copy values stored during previous steps into $_POST because they are needed in form_builder() to repopulate the form.
    if (is_array($_SESSION[$session_key])) {
      foreach ($_SESSION[$session_key] as $key => $val) {
        $_POST['submitted'][$key] = $val;
      }
    }

    // Store values from an intermediate stage of a multistep form in $_SESSION.
    if (is_array($form_values['submitted'])) {
      foreach ($form_values['submitted'] as $key => $val) {
        $_SESSION[$session_key][$key] = $val;
      }
    }
    return;
  }

  if (is_array($_SESSION[$session_key])) {
    // Merge any submission data stored in $_SESSION for multistep forms.
    foreach ($_SESSION[$session_key] as $key => $val) {
      $form_values['submitted'][$key] = $val;
    }
    unset($_SESSION[$session_key]);
  }

  // Perform post processing by components.
  _webform_client_form_submit_process($node, $form_values['submitted']);

  // Flatten trees within the submission.
  $form_values['submitted_tree'] = $form_values['submitted'];
  _webform_client_form_submit_flatten($node, $form_values['submitted'], $form_values['submitted']);

  // Perform additional submit processing.
  if (trim($node->additional_submit)) {
    // We use eval here (rather than drupal_eval) because the user needs access to local variables.
    eval("?>". $node->additional_submit);
  }

  // Save the submission to the database.
  if (!$form_values['details']['sid']) {
    // No sid was found thus insert it in the datatabase.
    $sid = webform_submission_insert($node, $form_values['submitted']);
  }
  else {
    // Sid was found thus update the existing sid in the datatbase.
    $sid = webform_submission_update($node, $form_values['details']['sid'], $form_values['submitted']);
  }

  // Check if this form is sending an email.
  if (isset($node->email) && !$form_values['details']['sid']) {
    $node->email = strip_tags($node->email);
    if (!empty($node->email)) {

      // Create a themed message for mailing.
      // Check for a node-specific message:
      $message = theme("webform_create_mailmessage_$node->nid", $form_values, $node, $sid);
      if (!$message) {
        // Otherwise use the generic form:
        $message = theme("webform_create_mailmessage", $form_values, $node, $sid);
      }

      // Build arrays of possible return email addresses and email subject lines from elements on the form.
      // Default values:
      $email_from_name = variable_get('webform_default_from_name', variable_get('site_name', ''));
      $email_from_address = variable_get('webform_default_from_email', variable_get('site_mail', ini_get('sendmail_from')));
      $email_subject_string = variable_get('webform_default_subject', t('Form submission from: '))  .' '. $node->title;
      $headers = array();

      // Check for empty values.
      if ($node->email_from_name == 'none') {
        $email_from_name = '';
      }
      if ($node->email_from_address == 'none') {
        $email_from_address = '';
      }
      if ($node->email_subject == 'none') {
        $email_subject_string = '';
      }

      // Search for user set FROM and SUBJECT fields.
      if (is_array($node->webformcomponents) && !empty ($node->webformcomponents)) {
        foreach ($node->webformcomponents as $cid => $component) {
          $type = $component['type'];
          // Find and set a custom FROM: field.
          if ($type == 'email' || $type == 'hidden' || $type == 'select') {
            if ($component['name'] == $node->email_from_address) {
              $email_from_address = check_plain($form_values['submitted'][$cid]);
            }
          }
          // Find and set a custom SUBJECT: field.
          if ($type == 'textfield' || $type == 'hidden' || $type == 'select') {
            if ($component['name'] == $node->email_from_name) {
              $email_from_name = check_plain($form_values['submitted'][$cid]);
            }
            if ($component['name'] == $node->email_subject) {
              $email_subject_string = check_plain($form_values['submitted'][$cid]);
            }
          }
          if ($type == 'email' && $component['extra']['carboncopy'] == 'Y' ) {
            $headers['Cc'] = check_plain($form_values['submitted'][$cid]);
          }
        }
      }

      // Assemble the FROM string.
      if (strlen($email_from_name) > 0) {
        $email_from_string = mime_header_encode($email_from_name) .' <'. $email_from_address .'>';
      }
      else {
        $email_from_string = $email_from_address;
      }

      // Verify that this submission is not attempting to send any spam hacks.
      if (_webform_submission_spam_check($node->email, $email_subject_string, $message, $email_from_string, $headers)) {
        watchdog('webform', t('Possible spam attempt from @remote_addr', array('@remote_add' => $_SERVER['REMOTE_ADDR'])) ."<br />\n". nl2br(htmlentities($message)), WATCHDOG_WARNING);
        drupal_set_message(t("Illegal information. Data not submitted."), 'error');
        return false;
      }
      // Additional headers.
      $headers['X-Mailer'] = 'Drupal Webform (PHP/'. phpversion() .')';

      // Mail the webform results.
      drupal_mail('webform-submission', $node->email, $email_subject_string, $message, $email_from_string, $headers);

      // Debugging output.
      if (variable_get('webform_debug', 0) >= 2) {
        drupal_set_message("E-mail Headers: <pre>". htmlentities(print_r($headers, true)) ."</pre>To: ". $node->email ."<br />From: ". htmlentities($email_from_string) ."<br />Subject: ". $email_subject_string ."<br />E-mail Body: <pre>". $message ."</pre>");
      }
    }
  }

  if (variable_get('webform_debug', 0) >= 2) {
    drupal_set_message('$form_values are: <pre>'. htmlentities(print_r($form_values, true)) .'</pre>');
    drupal_set_message('$_SERVER is: <pre>'. htmlentities(print_r($_SERVER, true)) .'</pre>');
    drupal_set_message('$_POST is: <pre>'. htmlentities(print_r($_POST, true)) .'</pre>');
  }

  if (variable_get('webform_debug', 0) >= 1) {
    watchdog('webform', t('Submission posted to %title', array('%title' => $node->title)) . l(t('Results'), 'node/'. $node->nid, NULL, 'sid='. $sid) ."<br />\n<pre>". htmlentities(print_r($form_values, TRUE)) ."</pre>", WATCHDOG_NOTICE);
  }

  // Check confirmation field to see if redirect should be to another node or a message.
  if (valid_url(trim($node->confirmation), true)) {
    $redirect = trim($node->confirmation);
  }
  elseif (preg_match('/^internal:/', $node->confirmation) && $node->redirect_post) {
    $path = preg_replace('/^internal:/', $base_url .'/', $node->confirmation);
    $redirect = trim($path);
  }
  elseif (preg_match('/^internal:/', $node->confirmation)) {
    $path = preg_replace('/^internal:/', '', $node->confirmation);
    $redirect = array(trim($path), 'sid='. $sid);
  }
  else {
    $redirect = array('node/'. $node->nid .'/done', 'sid='. $sid);
  }
  return $redirect;
}

/**
 * Post processes the submission tree with any updates from components.
 */
function _webform_client_form_submit_process($node, &$form_values, $parents = array(0)) {
  if (is_array($form_values)) {
    foreach ($form_values as $form_key => $value) {
      $cid = webform_get_cid($node, $form_key, $parents);
      if (is_array($value) && $node->webformcomponents[$cid]['type'] == 'fieldset') {
        array_unshift($parents, $cid);
        _webform_client_form_submit_process($node, $form_values[$form_key], $parents);
        array_shift($parents);
      }
    }
  }

  // We loop through components rather than the actual submission, because
  // some components (file) do not get things submitted in the $form_values.
  foreach ($node->webformcomponents as $cid => $component) {
    if ($component['pid'] == $parents[0]) {
      $submit_function = "_webform_submit_". $component['type'];
      if (function_exists($submit_function)) {
        $submit_function($form_values[$component['form_key']], $component); // Call the component process submission function.
      }
    }
  }
}

/**
 * Flattens a submitted form back into a single array representation (rather than nested fields)
 */
function _webform_client_form_submit_flatten($node, $fieldset, &$form, $parents = array(0)) {
  if (is_array($fieldset)) {
    foreach ($fieldset as $form_key => $value) {
      $cid = webform_get_cid($node, $form_key, $parents);

      if (is_array($value) && $node->webformcomponents[$cid]['type'] == 'fieldset') {
        array_unshift($parents, $cid);
        _webform_client_form_submit_flatten($node, $value, $form, $parents);
        array_shift($parents);
        unset($form[$form_key]);
        unset($form[$cid]);
      }
      else {
        // The order here is significant!
        unset($form[$form_key]);
        $form[$cid] = $value;
      }
    }
  }
}

/**
 * Prints the confirmation message after a successful submission.
 */
function _webform_confirmation($node) {
  drupal_set_title($node->title);
  $output = theme('webform_confirmation_'. $node->nid, $node, $_GET['sid']);
  if (empty($output)) {
    $output = theme('webform_confirmation', $node, $_GET['sid']);
  }
  return $output;
}

/**
 * Themable function for webform submission confirmation.
 * 
 * @param $node
 *   The webform node that has just been submitted.
 */
function theme_webform_confirmation($node, $sid) {
  $node->body = check_markup($node->confirmation, $node->format, FALSE);
  $node->links['webform_back'] = array(
    'href' => 'node/'. $node->nid,
    'title' => t('Go back to the form'),
  );
  return theme('node', $node, FALSE, TRUE);
}


/**
 * Theme the contents of emails sent by webform.
 * 
 * @param $form_values
 *   An array of all form values submitted by the user. The array contains three
 *   keys containing the following:
 *   - submitted: All the submitted values in a single array keyed by webform
 *     component IDs. Useful for simply looping over the values.
 *   - submitted_tree: All the submitted values in a tree-structure array, keyed
 *     by the Form Key values defined by the user.
 * @param $node
 *   The complete node object for the webform.
 * @param $sid
 *   The submission ID of the new submission.
 */
function theme_webform_create_mailmessage($form_values, $node, $sid) {
  global $user;

  $message = '';
  $message .=  t('Submitted on') .' '. format_date(time(), 'small') ."\n";
  $ip_address = $_SERVER['REMOTE_ADDR'];

  if ($user->uid) {
    $message .= t('Submitted by user') .": $user->name [$ip_address]\n";
  }
  else {
    $message .= t('Submitted by anonymous user') .": [$ip_address]\n";
  }

  $message .= "\n";
  $message .= t('Submitted values are');
  $message .= theme('webform_mail_fields', '', $form_values['submitted_tree'], $node);

  $message .= "\n\n";
  $message .= t("The results of this submission may be viewed at:") ."\n";
  $message .= url('node/'.$node->nid, "sid=". $sid, NULL, TRUE);

  return $message;
}

/**
 * Theme the fields portion of the emails sent by webform.
 * 
 * This function calls itself recursively to maintain the tree structure of
 * components in the webform. It is called intialy by
 * theme_webform_create_mailmessage().
 * 
 * @param $key
 *   The parent component ID we're currently printing.
 * @param $value
 *   The value of the component to be printed. May be an array of other components.
 * @param $node
 *   The full node object.
 * @param $indent
 *   The current amount of indentation being applied to printed components.
 */
function theme_webform_mail_fields($key, $value, $node, $indent = "") {
  // First check for component-level themes.
  $themed_output = theme("webform_mail_". $node->webformcomponents[$key]['type'], $value, $node->webformcomponents[$key]);
  if ($themed_output) {
    // Indent the output and add to message.
    $message .= $indent;
    $themed_output = rtrim($themed_output, "\n");
    $message .= str_replace("\n", "\n". $indent, $themed_output);
    $message .= "\n";
  }
  // Generic output for single values.
  elseif (!is_array($value)) {
    // Note that newlines cannot be preceeded by spaces to display properly in some clients.
    if ($node->webformcomponents[$key]['name']) {
      // If text is more than 60 characters, put it on a new line with space after.
      $long = (strlen($indent . $node->webformcomponents[$key]['name'] . $value)) > 60;
      $message .= $indent . $node->webformcomponents[$key]['name'] .":". (empty($value) ? "\n" : ($long ? "\n$value\n\n" : " $value\n"));
    }
  }
  // Else use a generic output for arrays.
  else {
    $message .= $indent . $node->webformcomponents[$key]['name'] .":\n";
    foreach ($value as $k => $v) {
      foreach($node->webformcomponents as $local_key => $local_value) {
        if ($local_value['form_key'] == $k) {
          $form_key = $local_key;
          break;
        }
      }
      $message .= theme('webform_mail_fields', $form_key, $v, $node, $indent ."  ");
    }
  }
  return ($message);
}

/**
 * Filters all special tokens provided by webform, such as %post and %profile.
 */
function _webform_filtervalues($string, $strict = TRUE) {
  global $user;

  // Setup default token replacements.
  $find = array('%username', '%useremail', '%site', '%date');
  $replace = array($user->name, $user->mail, variable_get('site_name', 'drupal'), format_date(time(), 'large'));

  // Provide a list of candidates for token replacement.
  $tokens = array(
    '%server' => $_SERVER,
    '%session' => $_SESSION,
    '%cookie' => $_COOKIE,
    '%get' => $_GET,
    '%post' => $_POST,
    '%request' => $_REQUEST,
    '%profile' => $user,
  );

  foreach ($tokens as $token => $variable) {
    if (strpos($string, $token) !== FALSE) {
      foreach ($variable as $key => $value) {
        $find[] = $token .'['. $key .']';

        // This special case for profile module dates.
        if ($token == '%profile' && is_array($value) && $value['year']) {
          $replace[] = format_date(strtotime($value['month'] .'/'. $value['day'] .'/'. $value['year']), 'custom', 'F j, Y', '0');
        }
        else {
          $replace[] = $value;
        }
      }
    }
  }

  $string = str_replace($find, $replace, $string);

  // Clean up any unused tokens.
  foreach (array_keys($tokens) as $token) {
    $string = preg_replace('/\\'. $token .'\[\w+\]/', '', $string);
  }

  if ($strict) {
    return filter_xss($string);
  }
  else {
    return $string;
  }
}

/**
 * Menu callback for admin/content/webform. Displays all webforms on the site.
 */
function webform_admin_content() {
  $result = db_query("SELECT nid, uid, title FROM {node} WHERE type = 'webform'");
  $nodes = array();
  while ($node = db_fetch_object($result)) {
    $nodes[] = $node;
  }

  return theme('webform_admin_content', $nodes);
}


/**
 * Generate a list of all webforms avaliable on this site.
 */
function theme_webform_admin_content($nodes) {
  $header = array(
    t('Title'),
    array('data' => t('View'), 'colspan' => '4'),
    array('data' => t('Operations'), 'colspan' => '2')
  );

  $rows = array();
  foreach ($nodes as $node) {
    $rows[] = array(
      l($node->title, 'node/'. $node->nid),
      l(t('Submissions'),'node/'. $node->nid .'/results'),
      l(t('Analysis'),'node/'. $node->nid .'/results/analysis'),
      l(t('Table'),'node/'. $node->nid .'/results/table'),
      l(t('Download'),'node/'. $node->nid .'/results/download'),
      node_access('update', $node) ? l(t('Edit'), 'node/'. $node->nid .'/edit') : '',
      user_access('clear webform results') ? l(t('Clear'), 'node/'. $node->nid .'/results/clear') : '',
    );
  }

  drupal_set_title($node->title);
  return theme('table', $header, $rows);
}

/**
 * Menu callback for node/[nid]/components.
 */
function webform_components($node, $cid = NULL, $op = 'edit') {
  include_once(drupal_get_path('module', 'webform') ."/webform_components.inc");
  $components = webform_load_components();

  if (isset($node->webformcomponents[$cid]) || $cid == 'new') {
    if ($op == 'delete') {
      return drupal_get_form('webform_component_delete_form', $node, $cid);
    }
    elseif ($cid == 'new' && in_array($op, array_keys($components))) {
      $component = array('type' => $op, 'name' => $_GET['name'], 'mandatory' => $_GET['mandatory'], 'pid' => $_GET['pid'], 'weight' => $_GET['weight']);
      return drupal_get_form('webform_component_edit_form', $node, $component);
    }
    elseif (isset($node->webformcomponents[$cid]) && $op == 'clone') {
      $component = $node->webformcomponents[$cid];
      unset($component['cid']); // Removing the CID creates a new component on submit.
      return drupal_get_form('webform_component_edit_form', $node, $component);
    }
    elseif (isset($node->webformcomponents[$cid])) {
      return drupal_get_form('webform_component_edit_form', $node, $node->webformcomponents[$cid]);
    }
  }

  return drupal_get_form('webform_components_form', $node);
}

/**
 * Menu callback for all content under admin/content/webform.
 */
function webform_results($node, $op = 'submissions') {
  include_once(drupal_get_path('module', 'webform') ."/webform_report.inc");
  include_once(drupal_get_path('module', 'webform') ."/webform_submissions.inc");

  drupal_set_title($node->title);

  switch ($op) {
    case 'analysis':
      return webform_results_analysis($node);
    case 'clear' :
      return drupal_get_form('webform_results_clear', $node);
    case 'table':
      return webform_results_table($node);
    case 'download' :
      return webform_results_download($node);
    case 'submissions':
    default :
      return webform_results_submissions($node);
      break;
  }
}

/**
 * Given a form_key and a list of form_key parents, determine the cid.
 * 
 * @param $node
 *   A fully loaded node object.
 * @param $form_key
 *   The form key for which we're finding a cid.
 * @param $original_parents
 *   An array of form keys that parent $form_key.
 * 
 */
function webform_get_cid($node, $form_key, $original_parents) {
  foreach ($node->webformcomponents as $cid => $component) {
    $parents = $original_parents;
    $pid = array_shift($parents);

    if ($component['form_key'] == $form_key) {
      if (empty($pid) && $component['pid'] == 0) {
        return $cid;
      }
      elseif (!empty($pid) && $pid != $cid) {
        $parent = $node->webformcomponents[$pid];
        if ($pid == webform_get_cid($node, $parent['form_key'], $parents)) {
          return $cid;
        }
      }
    }
  }
  return FALSE;
}

function _webform_safe_name($name) {
  $new = str_replace(
    array(' ','€','ƒ','Š','Ž','š','ž','Ÿ','¢','¥','µ','À','Á','Â','Ã','Ä','Å','Ç','È','É','Ê','Ë','Ì','Í','Î','Ï','Ñ','Ò','Ó','Ô','Õ','Ö','Ø','Ù','Ú','Û','Ü','Ý','à','á','â','ã','ä','å','ç','è','é','ê','ë','ì','í','î','ï','ñ','ò','ó','ô','õ','ö','ø','ù','ú','û','ü','ý','ÿ','Œ', 'œ', 'Æ', 'Ð', 'Þ', 'ß', 'æ', 'ð', 'þ'),
    array('_','E','f','S','Z','s','z','Y','c','Y','u','A','A','A','A','A','A','C','E','E','E','E','I','I','I','I','N','O','O','O','O','O','O','U','U','U','U','Y','a','a','a','a','a','a','c','e','e','e','e','i','i','i','i','n','o','o','o','o','o','o','u','u','u','u','y','y','OE','oe','AE','DH','TH','ss','ae','dh','th'),
    trim($name));
  $new = drupal_strtolower($new);
  $new = preg_replace('/[^a-z0-9_]/', '', $new);
  return $new;
}

/**
 * Convert an array of components into a tree
 */
function _webform_components_tree_build($src, &$tree, $parent, &$page_count) {
  foreach ($src as $cid => $component) {
    if ($component['pid'] == $parent) {
      _webform_components_tree_build($src, $component, $cid, $page_count);
      $tree['children'][$cid] = $component;
      $tree['children'][$cid]['page_num'] = $page_count;
      if ($component['type'] == 'pagebreak') {
        $page_count++;
      }
    }
  }
  return $tree;
}

/**
 * Flatten a component tree into a flat list.
 */
function _webform_components_tree_flatten($tree) {
  $components = array();
  foreach ($tree as $cid => $component) {
    if (isset($component['children'])) {
      unset($component['children']);
      $components[$cid] = $component;
      // array_merge() can't be used here because the keys are numeric.
      $children = _webform_components_tree_flatten($tree[$cid]['children']);
      foreach ($children as $ccid => $ccomponent) {
        $components[$ccid] = $ccomponent;
      }
    }
    else {
      $components[$cid] = $component;
    }
  }
  return $components;
}

/**
 * Helper for the uasort in webform_tree_sort()
 */
function _webform_components_sort($a, $b) {
  if ($a['weight'] == $b['weight']) {
    return strcasecmp($a['name'], $b['name']);
  }
  return ($a['weight'] < $b['weight']) ? -1 : 1;
}

/**
 * Sort each level of a component tree by weight and name
 */
function _webform_components_tree_sort($tree) {
  if (is_array($tree['children'])) {
    uasort($tree['children'], "_webform_components_sort");
    foreach ($tree['children'] as $cid => $component) {
      $return[$cid] = _webform_components_tree_sort($component);
    }
    $tree['children'] = $return;
  }
  return $tree;
}

/**
 * Load all necessary component.inc files into memory.
 */
function webform_load_components($return_all = FALSE, $reset = FALSE) {
  static $component_list, $enabled_list;

  if (!isset($component_list) || $reset) {
    $component_list = array();
    $enabled_list = array();
    $path = drupal_get_path('module', 'webform') ."/components";
    $files = file_scan_directory($path, '^.*\.inc$');
    foreach ($files as $filename => $file) {
      $enabled = variable_get('webform_enable_'. $file->name, 1);
      if ($return_all || $enabled) {
        include_once($filename);
        $component_list[$file->name] = t($file->name);
      }
      if ($enabled) {
        $enabled_list[$file->name] = t($file->name);
      }
    }
  }

  // Ensure only wanted components are returned, even all are loaded.
  return $return_all ? $component_list : array_intersect_assoc($component_list, $enabled_list);
}

