<?php

/**
 * @file
 * Provides a simple user interface for building and maintaining webforms.
 */

/**
 * Implements hook_entity_type_alter().
 */
function webform_ui_entity_type_alter(array &$entity_types) {
  if (isset($entity_types['webform'])) {
    /** @var \Drupal\Core\Entity\ContentEntityTypeInterface $webform_entity_type */
    $webform_entity_type = $entity_types['webform'];

    // Swap the 'default' webform handler with the webform UI entity form
    // and move the old webform source entity webform to a new 'source'
    // webform handler.
    $handlers = $webform_entity_type->getHandlerClasses();
    $handlers['form']['source'] = $handlers['form']['default'];
    $handlers['form']['default'] = 'Drupal\webform_ui\WebformUiEntityForm';
    $handlers['form']['duplicate'] = 'Drupal\webform_ui\WebformUiEntityForm';
    $webform_entity_type->setHandlerClass('form', $handlers['form']);
  }

  if (isset($entity_types['webform_options'])) {
    /** @var \Drupal\Core\Entity\ContentEntityTypeInterface $webform_entity_type */
    $webform_options_entity_type = $entity_types['webform_options'];

    // Swap the 'default' webform handler with the webform UI option form
    // and move the old webform option source entity webform to a new 'source'
    // webform handler.
    $handlers = $webform_options_entity_type->getHandlerClasses();
    $handlers['form']['source'] = $handlers['form']['default'];
    $handlers['form']['default'] = 'Drupal\webform_ui\WebformUiOptionsForm';
    $webform_options_entity_type->setHandlerClass('form', $handlers['form']);
  }

}
