<?php

/**
 * @file
 * Provides development tools Webform module.
 */

/**
 * Implements hook_entity_type_alter().
 */
function webform_devel_entity_type_alter(array &$entity_types) {
  if (isset($entity_types['webform'])) {
    /** @var \Drupal\Core\Entity\ContentEntityTypeInterface $entity_type */
    $entity_type = $entity_types['webform'];
    $handlers = $entity_type->getHandlerClasses();
    $handlers['form']['export'] = 'Drupal\webform_devel\Form\WebformEntityExportForm';
    $entity_type->setHandlerClass('form', $handlers['form']);
  }
}
