<?php

/**
 * @file
 * Install, update and uninstall functions for the Webform Test Bootstrap module.
 */

use Drupal\Core\Serialization\Yaml;

/**
 * Implements hook_install().
 */
function webform_bootstrap_test_module_install() {
  // Uninstall bootstrap theme.
  /** @var \Drupal\Core\Extension\ThemeHandlerInterface $theme_handler */
  $theme_handler = \Drupal::service('theme_handler');
  $theme_handler->install(['webform_bootstrap_test_theme', 'bootstrap']);

  // Set default theme to bootstrap.
  \Drupal::configFactory()->getEditable('system.theme')
    ->set('admin', 'webform_bootstrap_test_theme')
    ->set('default', 'webform_bootstrap_test_theme')
    ->save();

  // Set Bootstrap container and button classes.
  $container_classes = '
container-inline clearfix
form--inline clearfix
well
well well-sm
well well-lg
alert alert-warning
alert alert-danger
alert alert-success
alert alert-info
alert-dismissible';
  $button_classes = '
btn
btn btn-default
btn btn-primary
btn btn-success
btn btn-info
btn btn-warning
btn btn-danger
btn btn-link
btn-xs
btn-sm
btn-lg';
  \Drupal::configFactory()->getEditable('webform.settings')
    ->set('settings.form_classes', $container_classes)
    ->set('settings.button_classes', $button_classes)
    ->set('settings.confirmation_classes', $container_classes)
    ->set('settings.confirmation_back_classes', $button_classes)
    ->set('element.wrapper_classes', $container_classes)
    ->set('element.classes', $container_classes)
    ->save();

  // Set Bootstrap theme settings.
  \Drupal::configFactory()->getEditable('webform_bootstrap_test_theme.settings')
    ->set('modal_size', 'modal-lg')
    ->save();
}

/**
 * Implements hook_uninstall().
 */
function webform_bootstrap_test_module_uninstall() {
  // Restore default container and button classes.
  $default_config = Yaml::decode(file_get_contents(drupal_get_path('module', 'webform') . '/config/install/webform.settings.yml'));
  \Drupal::configFactory()->getEditable('webform.settings')
    ->set('settings.form_classes', $default_config['settings']['settings']['form_classes'])
    ->set('settings.button_classes', $default_config['settings']['button_classes'])
    ->set('settings.confirmation_classes', $default_config['settings']['confirmation_classes'])
    ->set('settings.confirmation_back_classes', $default_config['settings']['confirmation_back_classes'])
    ->set('element.wrapper_classes', $default_config['element']['wrapper_classes'])
    ->set('element.classes', $default_config['element']['classes'])
    ->save();

  // Set default theme to bartik.
  \Drupal::configFactory()->getEditable('system.theme')
    ->set('admin', 'seven')
    ->set('default', 'bartik')
    ->save();

  // Uninstall bootstrap theme.
  /** @var \Drupal\Core\Extension\ThemeHandlerInterface $theme_handler */
  $theme_handler = \Drupal::service('theme_handler');
  $theme_handler->uninstall(['webform_bootstrap_test_theme', 'bootstrap']);
}
